name: drago_pos_printer
description: flutter package for print or list down both wireless and bluetooth esc printer devices.
version: 1.1.1
homepage: https://github.com/selvam920/drago_pos_printer

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.0.2

  hex: ^0.2.0
  image: ^4.5.4
  connectivity_plus: ^7.0.0
  drago_usb_printer: ^0.1.2
  network_info_plus: ^7.0.0
  printing: ^5.14.2
  win32: ^5.14.0
  ffi: ^2.1.4
  gbk_codec: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.drago_pos_printer
        pluginClass: DragoPosPrinterPlugin
      windows:
        pluginClass: DragoPosPrinterPluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/drago_pos_printer/assets/capabilities.json
